Feature/task manager
OpusCapita/fsm-workflow pull request #2
Opened 2017-06-02 14:21 UTC by dzhitomirsky-sc

In this PR:
* implemented TaskManager as a single module with an ability to monitor tasks and executed automatic nodes
* added tests & docs
* added availableState, isOn methods to Machine class

2017-06-05 07:31 UTC, asergeev-sc requested changes
See inline code comments.
Styles/images and font should be removed later from repo and replaced with npm that is build from https://github.com/OpusCapita/opuscapita-ui.

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/Machine.js
> +  isOn({object}) {
I propose to rename method from 'isOn' to 'isStarted'

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/Machine.js
> +  availableAutoTransitions({object}) {
Let's rename availableAutoTransitions to availableAutomaticTransitions

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/MachineDefinition.js
> +  findAvailableTransitions({ from, event, object, context, auto=false } = {}) {
rename "auto" to "isAutomatic"
**P.S.** I think it is better to have "automatic" instead of "auto" in machine definition too

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/MachineDefinition.js
> +    const checkGuards = ({transition, guardKey = 'guards'}) => {
I don't like the idea of such kind of optimizations. When checking "automatic" transitions I would like to see it just as additional condition like ```.. && checkAutomatic(). Don't spread the logic about automatic transitions through whole method "findAvailableTransitions". Don't optimize the code that is far away from being a production one it is to be changed anyway. I would implement it differently:

```javascript
// inside the "findAvailableTransitions" method
checkAutomatic = (transition) => {
  if (isAutomatic) {
    // we don't need to check "automatic" transitions at all 
     return true;
  }
  // check if transition automatic conditions are fullfilled
  // return true or false
};

let foundTransitions = transitions.filter(transition => {
  return checkFrom(transition) && 
    checkEvent(transition) && 
    checkGuards(transition) &&
    checkAutomatic(transition);		          
});
```

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/Machine.js
> +  availableAutoTransitions({object}) {
Rename 'availableAutoTransitions' to 'availableAutomaticTransitions'

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/Machine.js
> +  isOn({object}) {
Rename 'isOn' to 'isStarted'

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-library/src/MachineDefinition.js
> +  findAvailableTransitions({ from, event, object, context, auto=false } = {}) {
Rename 'auto' to 'isAutomatic'

2017-06-05 07:31 UTC, asergeev-sc commented on fsm-task-manager/src/TaskManager.js
> +import { doUntil, killProcess } from './utils';
Method 'start' or 'create' is required for starting/creating new tasks ~= start machine for the object.

2017-06-05 07:31 UTC, asergeev-sc commented on examples/process/www/components/Container.react.js
> +import React, { PropTypes, PureComponent } from 'react';
ProcessManager should return list of tasks. Task "start"  and "sendEvent" should be done inside the ProcessManager, e.g. "update" takes place after successful event sending inside ProcessManager.

2017-06-05 07:51 UTC, dzhitomirsky-sc commented on fsm-library/src/Machine.js
> +  isOn({object}) {
My proposal is _isRunning_

2017-06-07 07:28 UTC, dzhitomirsky-sc commented
Please check out updated version.

2017-06-07 19:39 UTC, asergeev-sc approved these changes

2017-06-07 20:29 UTC, merged