Added ability to restrict states names #74
OpusCapita/fsm-workflow pull request #75
Opened 2018-06-08 11:52 UTC by estambakio-sc

#74

2018-06-08 13:30 UTC, estambakio-sc commented
Current props structure: 
```
schemaConfig = {
    state: {
      availableNames: [
        'inspectionRequired',
        'approvalRequired',
        'approved'
      ]
    }
}
```

2018-06-11 09:03 UTC, asergeev-sc requested changes

2018-06-11 09:03 UTC, asergeev-sc commented on packages/editor/src/components/StatesTable/StateEditor.react.js
> +    existingStates: PropTypes.arrayOf(PropTypes.string).isRequired,
- I would use 'usedNames'  instead of existingStates, also isRequired is not really required here (use [] by default for this prop)

2018-06-11 09:03 UTC, asergeev-sc commented on packages/editor/src/components/StatesTable/StateEditor.react.js
> +    stateConfig: PropTypes.shape({
- I would use and 'availableNames' for all possible passing state names -> e.g. show select box instead of input

2018-06-11 09:03 UTC, asergeev-sc commented on packages/editor/src/components/StatesTable/StateEditor.react.js
> +    fsmState: statePropTypes,
I would rename 'fsmState' it to 'value'

2018-06-11 09:03 UTC, asergeev-sc commented on packages/editor/src/components/StatesTable/StateEditor.react.js
> +    initialName: (this.props.fsmState || {}).name
Not so clear why we need 'initialName' if we have this info passed via props

2018-06-11 09:03 UTC, asergeev-sc commented on packages/editor/src/components/WorkflowEditor/WorkflowEditor.DOCUMENTATION.md
> +      // "initialState": "inspectionRequired",
I think we can return back FSM schema back into example to be used by default

2018-06-11 11:53 UTC, asergeev-sc approved these changes

2018-06-11 13:02 UTC, merged